### ISSUE TITLE
feat: state=absent

### ISSUE THREAD

**Issue by yajo** [geerlingguy/ansible-role-helm#5]
This role doesn't provide a way to undo it!

**Comment by geerlingguy** [comment]
@Yajo - For all my roles, I tend to set them up on servers where if I want something gone I'll either:

  1. (Preferred) Delete the server or container, and then rebuild a new one without the role.
  2. Write a few automation tasks to uninstall the tool and clean up any configuration.

I don't write uninstall automation because IMO that's a [fools errand](https://en.wikipedia.org/wiki/Fool%27s_errand) to maintain, and it's much better practice to habitually be able to destroy any server and rebuild it—or failing that, make sure you only test out a role on a server that is non-important and can quickly be rebuilt.

**Comment by philipp-intelliroad** [comment]
Tools like *apt* provide *remove* and *purge* commands. They exist because someone followed another philosophy for quite some time. Maybe for good reasons too.
